# This workflow will do a clean install of dependencies, optionally build, and run tests
# across different versions of node.
name: Test
on:
  push:
    branches:
      - '**' # make it run on any branch
      - '!main' # but exclude the 'main' and 'master' branches
      - '!master'
  pull_request:
    branches:
      - '**'
      - '!main'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '20.x' # whichever node versions you support
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn run build

      - name: Test
        run: yarn test
